spring:
  application.name: t1_test
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    recipient: ${MAIL_RECIPIENT}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE}
  security:
    secretKey: ${JWT_SECRET_KEY}

kafka:
  bootstrap:
    server: localhost:9092
  consumer:
    group-id: t1-test
  max:
    partition:
      fetch:
        bytes: 300000
    poll:
      records: 10
      interval:
        ms: 30000
  producer:
    enable: true
  topic:
    mail_notification: t1-test_mail_notification
  listener:
    poll-timeout: 5000
  session:
    timeout:
      ms: 15000


logging:
  level:
    ru:
      tarasov:
        testing: DEBUG
